const state = { moduleDir: "", script: "", lang: "zh", status: null, inputs: { patch: null, vuln: null }, repo: null, poll: null, confirmStep: 0, pending: null };
const T = {
  zh: { title:"假回锁 - 专家模式", heading:"专家模式", desc:"手动选择 ABL，分析 GBL 漏洞，并选择 EFI 或槽位刷写方案。", back:"返回普通模式", refresh:"刷新", waiting:"等待检测", unknown:"槽位未知", slot:"槽位状态", current:"当前槽位", target:"非活动槽", product:"机型", task:"任务状态", sources:"ABL 输入", patch:"Patch 源 ABL", patchHint:"用于生成 boot.efi；不要求自身有 GBL 漏洞。", vuln:"漏洞 ABL", vulnHint:"仅首次应用假锁或 OTA 槽位准备需要。", choose:"选择文件", none:"未选择", repoChecking:"Repo 检测中", repoReady:"Repo 已匹配当前机型，需通过 GBL 检测", mode:"操作方案", efi:"仅更新 EFI", efiHint:"不写 ABL，仅更新 persist/efisp 和 raw efisp。", first:"首次应用假锁", firstHint:"写入活动槽 ABL + EFI；高风险。", ota:"OTA 槽位准备", otaHint:"写入非活动槽 ABL + EFI。", warning:"这是高风险 bootloader 操作。开始前请核对机型、槽位、SHA-256 和 GBL 检测结果。", start:"确认并执行", plan:"执行计划", planWait:"请选择输入并完成分析。", risk:"高风险操作", confirmTitle:"确认执行", confirm:"确认按计划执行？", confirmActive:"即将写入当前活动槽 ABL。再次确认继续？", cancel:"取消", continue:"继续", execute:"确认执行", updateEfi:"更新并回读校验 EFI", flashAbl:"刷写并回读校验 ABL", backupAbl:"备份目标槽 ABL", logs:"实时日志", auto:"自动轮询最近 200 行", status:"状态", analyze:"分析中", ready:"可用", no:"不可用", present:"存在", absent:"不存在", unknownGbl:"无法判断", extract:"提取", patchResult:"Patch", size:"大小", sha:"SHA-256", source:"来源", invalid:"输入不可用", needVuln:"该方案需要 GBL 漏洞 ABL", needPatch:"Patch 源必须能生成 EFI", running:"任务运行中", done:"任务已完成", failed:"任务失败", repoNone:"未找到当前机型的 Repo 漏洞 ABL" },
  en: { title:"Fake Lock - Expert Mode", heading:"Expert Mode", desc:"Select ABL inputs, analyze GBL status, and choose an EFI or slot flashing plan.", back:"Back to normal mode", refresh:"Refresh", waiting:"Waiting", unknown:"Slot unknown", slot:"Slot Status", current:"Current slot", target:"Inactive slot", product:"Product", task:"Task status", sources:"ABL Inputs", patch:"Patch source ABL", patchHint:"Used to build boot.efi; it need not contain the GBL vulnerability.", vuln:"Vulnerable ABL", vulnHint:"Required only for first setup or OTA slot preparation.", choose:"Choose file", none:"Not selected", repoChecking:"Checking repo", repoReady:"Repo matched to this product; GBL check required", mode:"Operation", efi:"EFI only", efiHint:"Update persist/efisp and raw efisp without writing ABL.", first:"First fake-lock setup", firstHint:"Write active-slot ABL + EFI; high risk.", ota:"OTA slot preparation", otaHint:"Write inactive-slot ABL + EFI.", warning:"This is a high-risk bootloader operation. Verify product, slots, SHA-256, and GBL results.", start:"Confirm and execute", plan:"Execution plan", planWait:"Select inputs and finish analysis.", risk:"HIGH RISK", confirmTitle:"Confirm execution", confirm:"Confirm execution of the plan?", confirmActive:"The active-slot ABL will be overwritten. Confirm again to continue?", cancel:"Cancel", continue:"Continue", execute:"Confirm", updateEfi:"Update and verify EFI", flashAbl:"Flash and verify ABL", backupAbl:"Back up target-slot ABL", logs:"Live log", auto:"Auto-poll last 200 lines", status:"Status", analyze:"Analyzing", ready:"Ready", no:"Unavailable", present:"Present", absent:"Absent", unknownGbl:"Unknown", extract:"Extract", patchResult:"Patch", size:"Size", sha:"SHA-256", source:"Source", invalid:"Input unavailable", needVuln:"This mode requires a vulnerable ABL", needPatch:"Patch source must build EFI", running:"Task running", done:"Task completed", failed:"Task failed", repoNone:"No matching vulnerable ABL in repo" }
};
const el = id => document.getElementById(id);
function bridge(){ return globalThis.ksu || window.ksu || null; }
function out(raw){ if(typeof raw === "string"){ try { const x=JSON.parse(raw); return x.stdout ?? x.out ?? raw; } catch { return raw; } } return raw?.stdout ?? raw?.out ?? String(raw ?? ""); }
function shell(v){ return `'${String(v).replace(/'/g,"'\\''")}'`; }
function exec(c){ return out(bridge()?.exec?.(c)).replace(/\t/g,"\n"); }
function kv(s){ return Object.fromEntries(s.split(/\r?\n/).filter(Boolean).map(x=>{const i=x.indexOf("=");return i<1?[]:[x.slice(0,i),x.slice(i+1)];})); }
function run(action,...args){ return exec([`MODDIR=${shell(state.moduleDir)}`,"sh",shell(state.script),action,...args.map(shell)].join(" ")); }
function t(){ return T[state.lang]; }
function text(id,key){ if(el(id)) el(id).textContent=t()[key]; }
function applyLang(){ document.documentElement.lang=state.lang==="zh"?"zh-CN":"en"; document.title=t().title; text("pageHeading","heading"); text("heroDesc","desc"); text("backLink","back"); text("refreshButton","refresh"); text("lblSlotStatus","slot"); text("lblCurrentSlot","current"); text("lblTargetSlot","target"); text("lblProduct","product"); text("lblTaskStatus","task"); text("lblSources","sources"); text("lblPatchSource","patch"); text("patchFileButton","choose"); text("lblVulnSource","vuln"); text("vulnFileButton","choose"); text("lblMode","mode"); text("modeEfi","efi"); text("modeFirst","first"); text("modeOta","ota"); text("startButton","start"); text("lblPlan","plan"); text("lblLog","logs"); text("lblAutoPoll","auto"); text("warning","warning"); text("modalRisk","risk"); text("modalTitle","confirmTitle"); text("cancelConfirmButton","cancel"); el("patchHint").textContent=t().patchHint; el("vulnHint").textContent=t().vulnHint; el("modeEfiHint").textContent=t().efiHint; el("modeFirstHint").textContent=t().firstHint; el("modeOtaHint").textContent=t().otaHint; }
function formatAnalysis(a){ if(!a) return t().none; if(a.ERROR) return `${t().invalid}: ${a.ERROR}`; return `${t().source}: ${a.PATH}\n${t().size}: ${a.SIZE}\n${t().sha}: ${a.SHA256}\n${t().extract}: ${a.EXTRACT}\nGBL: ${a.GBL==="present"?t().present:a.GBL==="absent"?t().absent:t().unknownGbl}\n${t().patchResult}: ${a.PATCH}`; }
function analyze(kind,path){ if(!path) return; el(`${kind}Analysis`).textContent=t().analyze; const a=kv(run("expert-analyze",path)); state.inputs[kind]={...a,path}; el(`${kind}Analysis`).textContent=formatAnalysis(a); updatePlan(); }
function populateSelect(id, options){ const s=el(id); s.innerHTML=""; options.forEach(o=>{const x=document.createElement("option");x.value=o.path;x.textContent=o.label;s.appendChild(x);}); s.onchange=()=>analyze(id.startsWith("patch")?"patch":"vuln",s.value); }
function loadStatus(){ const s=kv(run("status")); state.status=s; el("currentSlot").textContent=s.CURRENT_SLOT||"-"; el("targetSlot").textContent=s.TARGET_SLOT||"-"; el("taskMessage").textContent=s.MESSAGE||t().waiting; el("slotChip").textContent=s.CURRENT_SLOT&&s.TARGET_SLOT?`${s.CURRENT_SLOT} → ${s.TARGET_SLOT}`:t().unknown; el("stateChip").textContent=s.RUNNING==="1"?t().running:`${t().status}: ${s.STATE||"idle"}`; el("product").textContent=state.product||"-"; refreshLog(); updatePlan(); clearTimeout(state.poll); state.poll=setTimeout(loadStatus,s.RUNNING==="1"?3000:8000); }
function refreshLog(){ try { el("logOutput").textContent=run("tail","200").trim()||"-"; } catch {} }
function updatePlan(){ const mode=document.querySelector('input[name="mode"]:checked')?.value||"efi"; const p=state.inputs.patch, v=state.inputs.vuln; let valid=!!p&&p.PATCH==="ok"; if(mode!=="efi") valid=valid&&!!v&&v.GBL==="present"; el("startButton").disabled=!valid||state.status?.RUNNING==="1"; el("planState").textContent=valid?t().ready:t().waiting; if(!p||!valid){el("planOutput").textContent=t().planWait;return;} const target=mode==="first"?state.status?.CURRENT_SLOT:state.status?.TARGET_SLOT; const steps=[`1. ${t().updateEfi}`]; if(mode!=="efi") steps.push(`2. ${t().backupAbl}`,`3. ${t().flashAbl}: abl${target}`); el("planOutput").textContent=`${t().current}: ${state.status?.CURRENT_SLOT}\n${t().target}: ${target}\n\n${t().patch}: ${p.PATH}\n${t().sha}: ${p.SHA256}\n\n${mode!=="efi"?`${t().vuln}: ${v.PATH}\n${t().sha}: ${v.SHA256}\n\n`:""}${steps.join("\n")}`; }
function closeConfirm(){ state.confirmStep=0; state.pending=null; el("confirmModal").classList.add("hidden"); el("confirmModal").setAttribute("aria-hidden","true"); }
function executePending(){ const x=state.pending; if(!x)return; const r=kv(run("expert-run",x.mode,x.p.path,x.v?.path||"",state.status.CURRENT_SLOT,x.p.SHA256,x.v?.SHA256||"")); closeConfirm(); if(r.STARTED!=="1") loadStatus(); else { el("stateChip").textContent=t().running; setTimeout(loadStatus,1000); } }
function openConfirm(mode,p,v){ state.confirmStep=1; state.pending={mode,p,v}; el("confirmText").textContent=t().confirm; el("nextConfirmButton").textContent=mode==="first"?t().continue:t().execute; el("confirmModal").classList.remove("hidden"); el("confirmModal").setAttribute("aria-hidden","false"); }
function nextConfirm(){ if(state.pending?.mode==="first"&&state.confirmStep===1){ state.confirmStep=2; el("confirmText").textContent=t().confirmActive; el("nextConfirmButton").textContent=t().execute; return; } executePending(); }
function token(){ return `x${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`; }
async function importFile(kind,file){ const tok=token(); const ready=kv(run("expert-import-start",tok)); if(ready.READY!=="1") throw Error("import start failed"); const bytes=new Uint8Array(await file.arrayBuffer()); const chunk=12288; for(let i=0;i<bytes.length;i+=chunk){ let s=""; for(const b of bytes.subarray(i,i+chunk)) s+=String.fromCharCode(b); const r=kv(run("expert-import-chunk",tok,btoa(s))); if(r.OK!=="1") throw Error("import chunk failed"); } const path=`${state.moduleDir}/tmp/expert/${tok}.img`; const opts=kind==="patch"?el("patchSelect"):el("vulnSelect"); const o=document.createElement("option"); o.value=path; o.textContent=`${file.name} (${bytes.length} bytes)`; opts.appendChild(o); opts.value=path; analyze(kind,path); }
async function init(){ try { const info=kv(exec('for d in /data/adb/modules/*/; do [ -f "${d}bin/bl_flasher.sh" ] && printf "MODULE=%s\n" "${d%/}" && break; done')); state.moduleDir=info.MODULE; state.script=`${state.moduleDir}/bin/bl_flasher.sh`; const s=kv(run("status")); state.lang=s.USER_LANG==="en"?"en":"zh"; applyLang(); const repo=kv(run("expert-repo")); state.product=repo.PRODUCT||"-"; el("repoCaption").textContent=repo.AVAILABLE==="1"?t().repoReady:t().repoNone; const base=[{path:`/dev/block/by-name/abl${s.CURRENT_SLOT}`,label:`abl${s.CURRENT_SLOT} (${t().current})`},{path:`/dev/block/by-name/abl${s.TARGET_SLOT}`,label:`abl${s.TARGET_SLOT} (${t().target})`}]; const repoOpt=repo.AVAILABLE==="1"?[{path:repo.PATH,label:`Repo ${repo.PRODUCT}${repo.VERSION?` (${repo.VERSION})`:""}`}]:[]; populateSelect("patchSelect",base.concat(repoOpt)); populateSelect("vulnSelect",base.concat(repoOpt)); loadStatus(); analyze("patch",base[0].path); analyze("vuln",repoOpt[0]?.path||base[0].path); } catch(e){ el("stateChip").textContent=`${t().failed}: ${e.message}`; el("startButton").disabled=true; } }
el("refreshButton").onclick=loadStatus; el("startButton").onclick=()=>{ const mode=document.querySelector('input[name="mode"]:checked').value,p=state.inputs.patch,v=state.inputs.vuln; if(!p||(mode!=="efi"&&!v))return; openConfirm(mode,p,v); }; el("cancelConfirmButton").onclick=closeConfirm; el("nextConfirmButton").onclick=nextConfirm; document.querySelectorAll('input[name="mode"]').forEach(x=>x.onchange=updatePlan); el("patchFileButton").onclick=()=>el("patchFile").click(); el("vulnFileButton").onclick=()=>el("vulnFile").click(); el("patchFile").onchange=e=>e.target.files[0]&&importFile("patch",e.target.files[0]); el("vulnFile").onchange=e=>e.target.files[0]&&importFile("vuln",e.target.files[0]); init();
